# 远程主题配置
remote_theme: papierkorp/jekyll-theme-horizon-flow
plugins:
  - jekyll-remote-theme

# 站点基本信息
title: 寒冬日志
description: 一个自用笔记

# 导航菜单
navigation:
  - title: 首页
    url: /index.html
  - title: 分类
    url: /categories.html
  - title: 标签
    url: /tags.html
  - title: 归档
    url: /archive.html

# 页脚上方的侧边栏（最多5个元素）
footer_sidebar:
  arrangement:
    - description
    - tags
    - categories
    - recentposts
  description:
    enabled: true
  tags:
    enabled: true
  categories:
    enabled: true
    